-- CREATE database reprocare_db;
-- USE reprocare_db;
CREATE TABLE appointments (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (255) NOT NULL,
email VARCHAR (255) NOT NULL,
date DATE NOT NULL,
time TIME NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
